-- 코드를 작성해주세요
ELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE DEVELOPERS.SKILL_CODE & (
    SELECT SUM(CODE) 
    FROM SKILLCODES 
    WHERE NAME IN ('Python', 'C#')
) > 0
ORDER BY ID ASC;
